[package]
cairo-version = "2.5.0"
name = "eternum"
version = "0.5.0"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.6.1-alpha.4" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "cairo-v2.5.4" }
cubit = { git = "https://github.com/ponderingdemocritus/cubit" }

[tool.dojo.env]
## dev
world_address = "0x177a3f3d912cf4b55f0f74eccf3b7def7c6144efeba033e9f21d9cdb0230c64"
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"

## realms.world
[profile.prod.tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/lore-machine/katana"
account_address = "0x6813c4b1c6fcae7a725939d064345aab44f9c5e05bb2f403554e076e744c3ce"
private_key = "0x6756c233b3636006e756c233b363600e056c7c606000000fb5d7ba443f6bf79"
world_address = "0x177a3f3d912cf4b55f0f74eccf3b7def7c6144efeba033e9f21d9cdb0230c64"
# dev
# world_address = "0x177a3f3d912cf4b55f0f74eccf3b7def7c6144efeba033e9f21d9cdb0230c64"

[[target.dojo]]

[lib]

[tool.dojo.world]
name = "Realms: Eternum"
description = "Rule the Hex"
cover_uri = "file://assets/bg.webp"
website = "https://alpha-eternum.realms.world/"

[tool.fmt]
sort-module-level-items = true
